SET SOLUTION_NAME=Calabonga.Chat.AuthServer
SET SOLUTION_PATH=%~dp0
SET WEB_PATH=%SOLUTION_PATH%%SOLUTION_NAME%\%SOLUTION_NAME%\%SOLUTION_NAME%.Web

dotnet run --project %WEB_PATH%\%SOLUTION_NAME%.Web.csproj